### ISSUE TITLE
Bering temperature products

### ISSUE THREAD

**Issue by Lewis-Barnett-NOAA** [afsc-gap-products/model-based-indices#54]
```[tasklist]
### Tasks
```

**Comment by sean-rohan-NOAA** [comment]
Just got back from survey this morning. I'll be starting to work on this on Monday.

**Comment by sean-rohan-NOAA** [comment]
EBS temperature data products are now available through the [coldpool package](https://github.com/afsc-gap-products/coldpool) as of version 3.0-1 ([release notes](https://github.com/afsc-gap-products/coldpool/releases/tag/v3.0-1)).

Information about how to access the data products is provided in the [Usage section of the README](https://github.com/afsc-gap-products/coldpool#usage).

Finalized EBS temperature data products are:
- Cold pool index
- Mean EBS bottom temperature
- Mean EBS surface temperature
- Mean EBS bottom temperature in strata < 100 m
- EBS bottom and surface temperature rasters

**NBS data have not been finalized yet.** I've generated a few preliminary products ahead of next week's CPT meeting that use NBS data. However, temperature products that use NBS data are provisional and will definitely show some slight changes by the time they're finalized. It's likely NBS data will be finalized sometime next week.

Provisional data products that use NBS data:
- Mean NBS bottom temperature
- Combined EBS and NBS bottom temperature rasters

Data products that use NBS data that have not been generated:
- Mean NBS surface temperature
- Combined EBS and NBS surface temperature rasters

**Comment by Lewis-Barnett-NOAA** [comment]
All temperature products are now available via the coldpool package, thanks Sean!
