### ISSUE TITLE
[tasks] GOA data pull via gapindex

### ISSUE THREAD

**Issue by zoyafuso-NOAA** [afsc-gap-products/model-based-indices#63]
Hi @coleary-noaa, @MargaretSiple-NOAA, @Lewis-Barnett-NOAA 

### Check that the data input that comes from gapindex to what was produced historically for modsquad. 

I compared the data inputs from gapindex to those that were uploaded to the modsquad folder before the 2023 modsquad production run. That script lives [here](https://github.com/afsc-gap-products/gap_products/blob/main/code/modsquad_bridge/goa/goa_vast_gapindex_data_bridge.R). The script uses an [excel spreadsheet](https://github.com/afsc-gap-products/gap_products/blob/main/code/modsquad_bridge/goa/2023_hindcast_datasources.xlsx) that holds the googledrive ids for each GOA dataset.  If you want to recreate the comparison and clone the gap_products repo, they both are [here](https://github.com/afsc-gap-products/gap_products/tree/main/code/modsquad_bridge/goa). I couldn't detect a difference but it might still be useful to do a quick check for our respective species when we're doing the vast-sdmtmb bridging. 

### Create a vignette/piece of code that GOA folks can use to do their data pulls like [R/Prepare_GOA_data.R](https://github.com/afsc-gap-products/model-based-indices/blob/main/R/Prepare_GOA_data.R).

We can work off of this template. I think going forward we should include HAULJOIN in the input to make it easier to track even though we don't use it in the models. @coleary-noaa, can you check that this piece of code works and maybe you can update the Prepare_GOA_data.R script. 

```
## Import gapindex package. Installation functions are provided below. 
## library(devtools)
## devtools::devtools::install_github("afsc-gap-products/gapindex")
library(gapindex)

## Connect to Oracle. Make sure you are on the NOAA internal network or VPN
sql_channel <- gapindex::get_connected()

## Set constants, adjust for the request. You can also specify a species 
## complex via a dataframe. See gapindex::get_data() or the example commented
## out below for dusky rockfish. 
years <- 1990:2023
species_code <- 21720
# species_code <- data.frame(SPECIES_CODE = c(30152, 30150), 
#                            GROUP = c(30152, 30152))

## Pull catch and haul data. `pull_lengths` = F speeds up the function by not
## pulling lengths/specimen data. By default, only hauls with ABUNDANCE_HAUL == 
## 'Y' are filtered.
gapindex_data <- gapindex::get_data(survey_set = "GOA",
                                    year_set = years,
                                    spp_codes = species_code,
                                    pull_lengths = FALSE,
                                    sql_channel = sql_channel)

## Calculate weight and numerical CPUE and zero-fill hauls
gapindex_cpue <- gapindex::calc_cpue(racebase_tables = gapindex_data)

## Format catch and effort data for VAST. Note: The `AreaSwept_km2` field set 
## to 1 when using CPUE in the `Catch_KG` field.
data_geostat <- with(gapindex_cpue, data.frame(year = YEAR,
                                               hauljoin = HAULJOIN,
                                               vessel = "missing",
                                               lat = LATITUDE_DD_START,
                                               lon = LONGITUDE_DD_START,
                                               catch_kg = CPUE_KGKM2,
                                               Area_swept_km2 = 1,
                                               pass = 0) )

## Save output...
````

**Comment by MargaretSiple-NOAA** [comment]
For folks using `gapindex` to compare model-based to design-based indices, here is a code chunk we can adapt to calculate the total biomass for each year (as opposed to pulling from the summary schemas like the GOA schema):
```
# Using gapindex instead of GOA schema:
dat <- gapindex::get_data(year_set = unique(DBE$YEAR),
                          survey_set = "GOA",                # change
                          spp_codes = 21720,                 # change
                          abundance_haul = "Y",
                          pull_lengths = TRUE)
cpue <- gapindex::calc_cpue(racebase_tables = dat)
biomass_stratum <- gapindex::calc_biomass_stratum(racebase_tables = dat,cpue = cpue)
biomass_subareas <- gapindex::calc_biomass_subarea(racebase_tables = dat,
                                                   biomass_strata = biomass_stratum)
DBE <- subset(biomass_subareas, AREA_ID==99903) # would need to change this for other regions
DBE <- DBE[,c('YEAR', 'SPECIES_CODE', 'BIOMASS_MT', 'BIOMASS_VAR')]
names(DBE)[names(DBE) == "BIOMASS_MT"] <- "TOTAL_BIOMASS"
DBE <- DBE[order(DBE$YEAR),]
DBE$BIOMASS_SD <- sqrt(DBE$BIOMASS_VAR)
DBE$BIOMASS_CV <- DBE$BIOMASS_SD / DBE$TOTAL_BIOMASS
```

Zack wrote some nice code for GOA Pcod MB-DB comparison which is [here](https://github.com/afsc-gap-products/model-based-indices/blob/main/species_specific_code/GOA/Gadus_macrocephalus/Compare_w_DBEs.R).
