### ISSUE TITLE
Bering Sea sumfish->gapindex data bridging summary

### ISSUE THREAD

**Issue by zoyafuso-NOAA** [afsc-gap-products/model-based-indices#64]
Hi @Lewis-Barnett-NOAA, @coleary-noaa, @EmilyMarkowitz-NOAA, @sowasser

I created a space in the gap_products Github [repo](https://github.com/afsc-gap-products/gap_products/tree/main/code/modsquad_bridge/bering_sea) to reproduce and compare the 1982-2022 Bering Sea (EBS and NBS) YFS and PCod wCPUE, nCPUE, and age cpue datasets pulled using sumfish vs gapindex. I think I remember Sophia and Lewis in the past saying that pollock has a separate workflow so I did not include pollock in this exercise. I also created a [template](https://github.com/afsc-gap-products/model-based-indices/blob/main/R/Prepare_EBS_NBS_data_gapindex.R) Bering Sea gapindex data pull that we can work with and put it in the R/ folder. 

## Summary of the scripts used to perform bridging
- [EBS_VAST_Bridging_gapindex.R](https://github.com/afsc-gap-products/gap_products/blob/main/code/modsquad_bridge/bering_sea/EBS_VAST_Bridging_gapindex.R) produces these data via gapindex
- [EBS_VAST_Bridging_sumfish.R](https://github.com/afsc-gap-products/gap_products/blob/main/code/modsquad_bridge/bering_sea/EBS_VAST_Bridging_sumfish.R) produces these data using sumfish. Follows the [Prepare_EBS_NBS_Data.R](https://github.com/afsc-gap-products/model-based-indices/blob/main/R/Prepare_EBS_NBS_data.R) script
- [EBS_VAST_Index_Bridging.R](https://github.com/afsc-gap-products/gap_products/blob/main/code/modsquad_bridge/bering_sea/EBS_VAST_Index_Bridging.R) compares the two sources

## Summary of the gapindex-sumfish bridging of VAST data pulling

**Weight catch and effort data for biomass index**: no difference between the sumfish and gapindex data pulls for YFS and PCod. Yay.

**Numerical catch and effort data for abundance index**. There are a handful of hauls where a positive weight was recorded but numbers were not collected. The sumfish version of the dataset assumes these values as zero whereas these hauls are removed in the gapindex version. The number of hauls with this discrepancy is 9 for YFS and 7 for PCod. This doesn’t affect the YFS workflow because numbers are not modelled. 

**Age CPUE**: In addition to the hauls identified previously, there are a larger handful of hauls where there are positive weights and numbers data but no associated length information (115 total YFS hauls and 40 PCod hauls). The sumfish version of the age cpue dataset assumes these hauls to have 0 cpue whereas these hauls are removed from the gapindex version.

Jason mentioned this in issue #32  and I also noticed that there are some data complications when partitioning unsexed individuals (SEX = 3) in the sizecomp data across ages when the alks are often created with individuals that are sexed. SEX = 3 individuals have their own ALK in our workflow whereas in the design-based composition production, the SEX = 3 ALK is created using all sexes combined. Doing it the latter way may help account for all of the unsexed length individuals but I don't want to propose prioritizing this change given the software bridging that we are doing this year. 

Let me know if you want to see any details about this exercise, I just wanted to start with the main points.

**Comment by Lewis-Barnett-NOAA** [comment]
Thanks Zack, I think the transition was very smooth.
