### ISSUE TITLE
GOA data pull script revisions

### ISSUE THREAD

**Issue by Lewis-Barnett-NOAA** [afsc-gap-products/model-based-indices#69]
@zoyafuso-NOAA thanks for the updated data pull script.  I made a few edits.

One little ask: in addition to the species codes, please incorporate the scientific names in a new column called "species"

**Comment by zoyafuso-NOAA** [comment]
Hey @Lewis-Barnett-NOAA, take a look at the new script. I think somewhere in the gitignore file is preventing the pushing of a meshes/ directory. I'm not sure how to fix that.

**Comment by Lewis-Barnett-NOAA** [comment]
Thanks Zack, looks good. 

I fixed the .gitignore file so that the meshes and extrapolation grid folders and their contents are pushed to the remote.
